#! /usr/bin/env bash

# language/java/check
# CREATED: 2018-10-01
# UPDATED: 2018-10-02
# VERSION: 1.0.1
# AUTHOR:  wlharvey4
# ABOUT:   check is a shell program to take user input and run Makefile
# NOTES:
# CHANGE-LOG:
# .........................................................................
# 2018-10-02T13:25 version 1.0.1
# - implemented Bash version check, USAGE message, switch statement;
# - need to implement init function
# .........................................................................
# 2018-10-02T17:50 version 1.1.0
# - implemented init function
# .........................................................................
# 2018-10-03T06:15 version 1.2.0
# - refactored to protected an existing Code Challenge and JSON data file
#   but add a java/ directory only;
# -------------------------------------------------------------------------

bash --version | grep --quiet 'version 4\.' || {
  echo This program depends upon Bash version 4.
  echo you are running $(sh --version)
  exit
}

USAGE() {
cat << END
This is Code-Challenges-Intl
----------------------------
./check CODE-CHALLENGE          RUN THE CODE CHALLENGE TESTS
				e.g., ./check fizzbuzz
./check -h|--help|--usage       HELP MESSAGE
./check clean CODE-CHALLENGE    CLEAN CLASS FILES
				e.g. ./check clean fizzbuzz
./check init NEW-CODE-CHALLENGE INITIALIZE NEW CODE CHALLENGE TEMPLATES
				e.g. ./check init blah
END
}

INIT() {
  [ -d ../../challenges/${1,}/java ] && { echo ${1,} exists; exit; }
  echo creating challenges/$1/java...
  echo moving templates into challenges/${1,}/java...
  [ -e ../../challenges/${1,}/${1,}.json ] || cp -v templates/challenges/cc/cc.json ../../challenges/${1,}/${1,}.json
  cp -nrv templates/challenges/cc/java ../../challenges/${1,}/
  echo
  echo updating template names...
  find ../../challenges -name CC.java -execdir mv -v {} ${1^}.java \;
  echo
  echo updating template internals for:
  ( cd ../../
  for file in challenges/$1/java/*.java
  do
    echo "...$file"
    sed -i '' \
      -e 's/<cc>/'${1,}'/g' \
      -e 's/<CC>/'${1^}'/g' \
      -e 's/<DATE>/'$(date "+%Y-%m-%dT%H:%M:00")'/g' \
      $file
  done
  echo
  echo Successfully completed initializing Code Challenge templates for ${1^}
  )
}


case $1 in
*help|-h|*usage|*USAGE)
	USAGE
	;;
'clean')
	[ -z $2 ] && { echo; echo ERROR\! see usage; echo; USAGE; exit; }
	make clean cc=${2,}
	;;
'init')
	[ -z $2 ] && { echo; echo ERROR\! see usage; echo; USAGE; exit; }
	INIT ${2,}
	;;
*)
	[ -z $1 ] && { echo; echo ERROR\! see usage; echo; USAGE; exit; }
	make run SHELL=$(which bash) cc=${1,}
	;;
esac
